if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Window and session settings
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard

# Use Vi mode
set-window-option -g mode-keys vi

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind-key x kill-pane

bind -n M-Down resize-pane -D
bind -n M-Up resize-pane -U
bind -n M-Left resize-pane -L
bind -n M-Right resize-pane -R
bind -n M-Space select-layout next

set -g mouse on

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g @plugin 'ddzero2c/tmux-easymotion'
bind-key -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle;
bind-key -T copy-mode-vi v send-keys -X begin-selection;
bind-key -T copy-mode-vi V send-keys -X select-line;



set -g @plugin 'seebi/tmux-colors-solarized'
set -g @colors-solarized 'dark'

set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="C-f"
TMUX_FZF_OPTIONS="-p -w 80% -h 80% -m"

set -g status-right '| %a, %d-%b %H:%M | CPU: #{cpu_percentage} | #H'
set -g status-right-length 80

bind-key i neww bash -c "cht.sh"
bind-key g run-shell "tmux neww -c '#{pane_current_path}' 'lazygit'"


bind-key C-c new-session

bind-key f popup -h 80% -w 80% -E "sh -c '
  file=\$(fd . ~/workspace/ ~/dev ~/Documents ~/Downloads ~/.dotfiles \
    --type f --hidden --exclude .git \
    | fzf --layout=reverse --border --ansi --height=100% \
          --preview \"bat --style=numbers --color=always {}\")
  [ -n \"\$file\" ] && tmux new-window -n \"\$(basename \"\$file\")\" \"nvim \\\"\$file\\\"\"
'"

# Reload config file
unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux configuration reloaded"

# run '~/.tmux/plugins/tpm/bin/install_plugins'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


